spring:
  datasource:
    username: root
    password: 123456
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
  #禁用模板缓存
  thymeleaf:
    cache: false
mybatis:
  configuration:
    #_转驼峰命名
    map-underscore-to-camel-case: true
    #打印出select语句
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
